name: Java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - java/**
jobs:
  push:
    name: "images:java_${{ matrix.version }}-${{ matrix.vendor }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [8, 11, 16, 17, 21]
        vendor: [temurin, semeru]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java
          file: ./java/${{ matrix.version }}/${{ matrix.vendor }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/PizzabyteLLC/images:java_${{ matrix.version }}-${{ matrix.vendor }}
